version: '3.9'

services:
  db:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432


